### ISSUE TITLE
Missing Setup Instructions in Readme.md

### ISSUE THREAD

**Issue by setiadeepanshu01** [tarikrazine/multi-User-Chatbot-langChain-pinecone#1]
Could you please add detailed instructions on setting up the project and deploying over Cloud?

**Comment by tarikrazine** [comment]
I will try to add this as soon as possible with instruction to deploy it in vercel

**Comment by tarikrazine** [comment]
I Just added the readme file hope this will be helpful, and for the deployment will be done soon 🙂

**Comment by setiadeepanshu01** [comment]
Thanks @tarikrazine can you add current UI screenshot, will be helpful to suggest improvements etc.

**Comment by tarikrazine** [comment]
sure i will
