### ISSUE TITLE
Missing the crawler part that creates the embeddings? 

### ISSUE THREAD

**Issue by thorwebdev** [tarikrazine/multi-User-Chatbot-langChain-pinecone#2]
I was exploring this repository, but from what I can see it is missing the crawler part that is generating the embeddings in pinecone? Is that correct or am I missing something here?

**Comment by tarikrazine** [comment]
I was thinking of doing this separately. I'm looking to do this in a different way, using a free AI model to generate the vector embedding. I will add this to the README file when I'm finished.

**Comment by tarikrazine** [comment]
fixed
